import React, { useEffect, useState } from "react";
import type { InferGetServerSidePropsType, GetServerSideProps } from "next";
import { useRouter } from "next/router";
import s from "./single.module.scss";
import Image from "next/image";
import Head from "next/head";

interface Products {
  products: Det[];
}
interface Det {
  id: string;
  name: string;
  title: string | any;
  brand: string;
  price: number | any;
  color: string;
  country: string;
  size: number;
  description: string;
  img: string;
}

type Repo = {
  name: string;
  stargazers_count: number;
};

export const getStaticPaths = async () => {
  const res = await fetch(`http://localhost:3000/api`);
  const repo = await res.json();

  const paths = repo?.products?.map((p: any) => {
    return {
      params: {
        id: `${p?.id}`,
      },
    };
  });

  return {
    paths,
    fallback: true,
  };
};

export const getStaticProps = async (context: any) => {
  const { params } = context;

  return { props: { params } };
};

export default function Single({ params }: any) {
  const id = params?.id;

  const [mal, setMal] = useState<Det | null>(null);
  console.log(mal);

  useEffect(() => {
    const data = fetch(`http://localhost:3000/api/${id}`)
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        setMal(data?.product);
      });
  }, [id]);

  return (
    <>
      <Head>
        <title>{mal?.name}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={s.single}>
        <div className={s.single_card}>
          <div>
            <h1>{mal?.name}</h1>
          </div>
          <div className={s.single_flex}>
            <div className={s.single_img}>
              <Image src={mal?.img || ""} width={600} height={400} />
            </div>
            <div className={s.single_info}>
              <div>
                <p> Уникальное значение : _{mal?.id}</p>
              </div>
              <div></div>
              <div>
                <p>
                  {mal?.title.length > 100
                    ? `${mal?.title.slice(0, 100)} ... `
                    : mal?.title}{" "}
                </p>
              </div>

              <div>
                <p>
                  Модель :<span>{mal?.brand}</span>
                </p>
                <p>
                  Произведено в :<span>{mal?.country}</span>
                </p>
                <p>
                  Цвет :<span>{mal?.color}</span>
                </p>
                <p>
                  Размер :<span>{mal?.size}</span>
                </p>
              </div>
            </div>
            <div className={s.single_buy}>
              <div>
                <h3>{mal?.price} $</h3>
                <h5>{mal?.price + mal?.price * 0.1} $</h5>
              </div>
              <div>
                <span>Информация о доставке:</span>
                <p>
                  Стандартная доставка Доставка от 4 часов до 3 дней исходя от
                  адреса доставки
                </p>
              </div>
              <div>
                <button> Купить в один клик </button>
                <button> Добавить в корзину </button>
              </div>
            </div>
          </div>
          <div>
            <h2>Описание</h2>
            <br />
            <p>{mal?.description}</p>
          </div>
        </div>
      </div>
    </>
  );
}

// id: string;
// name: string;
// title: string;
// brand: string;
// price: number;
// color: string;
// country: string;
// size: number;
// img: string;
